baseURL = 'https:/chrplr.github.io/www-pallier-org/'
languageCode = 'en-us'
title = 'Christophe Pallier website'
theme = 'hugo-theme-relearn'

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'print']
  section = ['html', 'rss', 'print']

[[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 20

# [[menu.main]]
#   name = "Documentation 2"
#   url = "/docs2-sphinx/"
#   weight = 20

[[menu.main]]
    name = "Download PDF"
    url = "/docs/manual.pdf"
    weight = 30

theme = "hugo-theme-relearn"

[params]
  # Link to the root of your rep
  editURL = "https://github.com/chrplr/www-pallier-org/edit/main/hugo-site/content/"
  themeVariant = "mine"
  # Optional: Relearn specific settings
  showBreadcrumbs = true

[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-file-pdf'></i> Download PDF Manual"
  url = "/docs/manual.pdf"
  weight = 10

[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-external-link-alt'></i> Sphinx Technical Docs"
  url = "/docs/index.html"
  weight = 20
